name: Feature Request
description: Suggest a new feature or improvement for Aurora Shell
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you'd like.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this feature be useful? Is it related to a problem you're experiencing?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Related Module
      description: Which module does this relate to?
      options:
        - Theme Changer
        - Dock
        - No Overview
        - Pip On Top
        - New Module
        - Other / General
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
